### ISSUE TITLE
Перевірка на число.

### ISSUE THREAD

**Issue by Sashko26** [3A43Mka/euro-diffusion#1]
Привіт. Думаю, що Ваш код став би якіснішим, коли Ви добавили б **перевірку на число** елеметів стрічки data[i] в умовній конструкції **на 41 рядку** коду файлу input.js : https://github.com/3A43Mka/euro-diffusion/blob/6ed61a586ac7ba64e8bd2c4c3d0df868366e7f8a/src/input.js#L40-L44

**Comment by 3A43Mka** [comment]
Дякую за коментар, було додано перевірку на число
