### ISSUE TITLE
Перевірка файлу на існування.

### ISSUE THREAD

**Issue by Sashko26** [3A43Mka/euro-diffusion#2]
Привіт. Припускаю, що Ваш код став би якіснішим, якби Ви робили **перевірку файлу на існування** перед його прочитанням за шляхом "filepath" у функції getLines() в файлі input.js (30-33 рядки коду). У випадку, якщо файл не існує, ви могли б обробити цей випадок. 
https://github.com/3A43Mka/euro-diffusion/blob/6ed61a586ac7ba64e8bd2c4c3d0df868366e7f8a/src/input.js#L30-L33

**Comment by 3A43Mka** [comment]
Дякую за коментар, було додано обробку ситуації коли файлу не існує
