### ISSUE TITLE
Sorting question

### ISSUE THREAD

**Issue by IanaKhitsko** [3A43Mka/euro-diffusion#4]
https://github.com/3A43Mka/euro-diffusion/blob/3a601bb4b33afe8d96a0e1b99e1d61b8d7ece1d6/src/map.js#L48

Can we just return here c1.name - c2.name ?

**Comment by 3A43Mka** [comment]
We can't subtract strings in JavaScript, we will always get Nan. But we can use greater or less operators for sorting.
