### ISSUE TITLE
Reading countries count

### ISSUE THREAD

**Issue by IanaKhitsko** [3A43Mka/euro-diffusion#5]
https://github.com/3A43Mka/euro-diffusion/blob/3a601bb4b33afe8d96a0e1b99e1d61b8d7ece1d6/src/input.js#L10

why +lines[iterator] ? (Why + is here?)

**Comment by IanaKhitsko** [comment]
same question for other data

**Comment by 3A43Mka** [comment]
In JavaScript we can use + operator once to cast strings to numbers, since we are reading from file, this value is a string initially, then we cast it to number.
