### ISSUE TITLE
Remove local?

### ISSUE THREAD

**Issue by IanaKhitsko** [3A43Mka/euro-diffusion#6]
https://github.com/3A43Mka/euro-diffusion/blob/3a601bb4b33afe8d96a0e1b99e1d61b8d7ece1d6/src/map.js#L24

Consider removing local variable, that is used only once. OR. You can introduce it before condition, then check if (city !== undefined) {...}

Same for next cycle

**Comment by 3A43Mka** [comment]
Thanks for the suggestion, fixed.
